In [1]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
na1 = np.array([1,2,3])   # creating array

In [4]:
na1

array([1, 2, 3])

In [5]:
na2 = np.array([1,2,3.0])

In [6]:
na2

array([1., 2., 3.])

In [7]:
na3 = np.array([1,2,3,"a"])

In [8]:
na3

array(['1', '2', '3', 'a'], dtype='<U11')

In [9]:
np.random.random(5)

array([0.91780256, 0.60847925, 0.42885506, 0.78009284, 0.57327851])

In [10]:
np.random.rand(2,5)

array([[0.94361326, 0.56060519, 0.33708311, 0.87257603, 0.2225311 ],
       [0.2408221 , 0.11303811, 0.41858328, 0.35483628, 0.70480314]])

In [11]:
np.random.randn(2,5)  # value in standard deviation

array([[ 0.50564183,  0.88342798,  1.07291908, -0.65055573,  0.7231115 ],
       [-0.49282319, -1.48453157,  0.89400662,  0.3719501 ,  0.06600605]])

### Getting Values between 2 numbers

In [12]:
np.random.randint(10,100,20)    # (start,end,count of values)

array([16, 27, 35, 12, 17, 34, 70, 79, 92, 59, 53, 37, 87, 54, 55, 29, 74,
       97, 60, 87])

### Arrange

In [13]:
np.arange(0,100,2,float)   #(start, stop, step,dtype)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

### linspace

In [14]:
np.linspace(0,100,20).astype(int)   # (start, stop, number of values)

array([  0,   5,  10,  15,  21,  26,  31,  36,  42,  47,  52,  57,  63,
        68,  73,  78,  84,  89,  94, 100])

### Creating array of zeroes and ones

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### creating 2'D Array

In [17]:
np.empty((4,4),int)    # return an array of given shape with random numbers

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1436,       0],
       [      0, 7340097,       0, 7602273]])

In [18]:
np.full((4,4),fill_value = 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.identity((5),dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
np.eye(5,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.eye(5,5,3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.eye(5,5,-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### Array Attributes

In [24]:
na2 = np.eye(5,5,-2)

In [25]:
na2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
na2.shape

(5, 5)

In [27]:
na2.size

25

In [28]:
na2.dtype

dtype('float64')

In [29]:
na2.ndim

2

### Reshape

In [30]:
na3 = np.random.rand(2,4)
na3

array([[0.46190135, 0.59097681, 0.42868907, 0.89391979],
       [0.63056638, 0.26914131, 0.92028669, 0.11584028]])

In [31]:
na3.reshape(4,2)

array([[0.46190135, 0.59097681],
       [0.42868907, 0.89391979],
       [0.63056638, 0.26914131],
       [0.92028669, 0.11584028]])

In [32]:
na3 = na3.reshape(4,2)

In [33]:
na3

array([[0.46190135, 0.59097681],
       [0.42868907, 0.89391979],
       [0.63056638, 0.26914131],
       [0.92028669, 0.11584028]])

### Array indexing

In [34]:
na3[1][1]

0.893919786529055

In [35]:
na3[2][1]

0.2691413109039634

In [36]:
na3[2][0]

0.6305663777773048

In [37]:
na3[3][0]

0.9202866933695124

### Array Sliciing

 - array_name = [row_start:row_end, col_start:col_end]

In [38]:
na3

array([[0.46190135, 0.59097681],
       [0.42868907, 0.89391979],
       [0.63056638, 0.26914131],
       [0.92028669, 0.11584028]])

In [39]:
na3[0:3,0]      # array_name = [row_start:row_end, col_start:col_end]

array([0.46190135, 0.42868907, 0.63056638])

In [40]:
na3[0:3,0:2]

array([[0.46190135, 0.59097681],
       [0.42868907, 0.89391979],
       [0.63056638, 0.26914131]])

In [41]:
na3[0:3,0:1]

array([[0.46190135],
       [0.42868907],
       [0.63056638]])

In [42]:
na3[1,1]

0.893919786529055

### Creating 2'D Array

In [43]:
na4 = np.array([(1,2,3),(4,5,6)])

In [44]:
na4

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
na4.ndim

2

In [46]:
na4[0]

array([1, 2, 3])

In [47]:
na4[1,2]

6

In [48]:
na4[1][1]

5

### Arithmatic operation

In [49]:
na5 = np.array([[1,2,3],[4,5,6]])

In [50]:
na6 = np.array([[2,2,3],[4,4,6]])

In [51]:
na5

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
na6

array([[2, 2, 3],
       [4, 4, 6]])

In [53]:
na5 +na6

array([[ 3,  4,  6],
       [ 8,  9, 12]])

In [54]:
na5 - na6

array([[-1,  0,  0],
       [ 0,  1,  0]])

In [55]:
na5/na6

array([[0.5 , 1.  , 1.  ],
       [1.  , 1.25, 1.  ]])

In [56]:
na5.min()

1

In [57]:
na5.max()

6

In [58]:
na5

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
na5.var()

2.9166666666666665

In [60]:
na5.std()

1.707825127659933

In [61]:
na7 = np.array([50,60,70])

In [62]:
na7.mean()

60.0

In [63]:
na7.std()

8.16496580927726

In [64]:
na7.var()

66.66666666666667

In [65]:
na7

array([50, 60, 70])

In [66]:
np.square(na7)

array([2500, 3600, 4900], dtype=int32)

In [67]:
na5

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.square(na5)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [69]:
na5.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### Concatenate

In [70]:
np.concatenate([[1,2,3],[3,4,5]]) # concat list1 and list2 into an array

array([1, 2, 3, 3, 4, 5])

### Flatten Array

In [71]:
na5

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.ndarray.flatten(na5)  # which return 1'D array

array([1, 2, 3, 4, 5, 6])

### Iterating through array

In [73]:
na5

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
for i in na5:
    print(i)

[1 2 3]
[4 5 6]


In [75]:
for row_num,i in enumerate(na5):
    for j in range(0,na5.shape[1]):
        print("row",row_num,"column num",j, "value",i[j])

row 0 column num 0 value 1
row 0 column num 1 value 2
row 0 column num 2 value 3
row 1 column num 0 value 4
row 1 column num 1 value 5
row 1 column num 2 value 6


### Enumerate

In [76]:
for position_num,i in enumerate(["a","b","c"]):
    print(position_num,i)

0 a
1 b
2 c


### practice_study

In [77]:
sa = np.array([1,2,3,"vijay"])

In [79]:
type(sa)

numpy.ndarray

In [80]:
sa

array(['1', '2', '3', 'vijay'], dtype='<U11')

In [82]:
sa1= np.array(["vijay",123, 34.45,6+5j])

In [83]:
sa1

array(['vijay', '123', '34.45', '(6+5j)'], dtype='<U64')

In [84]:
sa3 = np.array([1,2,3,4])

In [85]:
sa3/2

array([0.5, 1. , 1.5, 2. ])

In [86]:
ls=[1,2,3]

In [87]:
ls/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'