In [4]:
import numpy as np

### Random

#### rand()

 - the function is used to generate a random value between 0 to 1
    
     

In [5]:
x = np.random.rand(4)
x

array([0.49135284, 0.63782687, 0.71024974, 0.18676653])

In [7]:
x1 = np.random.rand(4)
x1

array([0.82111069, 0.97270254, 0.4045389 , 0.18375101])

In [11]:
x2 = np.random.rand(3,3)
x2

array([[0.65741383, 0.12487126, 0.13269014],
       [0.74153246, 0.64394779, 0.26296652],
       [0.65753643, 0.07336913, 0.2216868 ]])

#### randn()

 - the function is used to generate a random value close to zero. this may return **positive or negative** numbers as well.

In [15]:
x3 = np.random.randn(3)
x3

array([-0.15863263, -0.26903815, -2.63718756])

In [17]:
x4 = np.random.randn(3,3)
x4

array([[ 0.58063926,  1.09705301, -2.21580932],
       [-1.72165327,  1.87819151, -0.17328454],
       [-0.61440152, -0.7773911 ,  1.1231792 ]])

#### ranf()

 - the function for doing random sampling  in numpy, it returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0)
 
 
 - it will give Excluding 1.0

In [23]:
x5 = np.random.ranf(3)
x5

array([0.89733484, 0.7963729 , 0.79524299])

#### randint()

 - the function is used to generate a random number between a given range

#### Syntax

 - np.random.randint( min, max, size,dtype )

In [29]:
x6 = np.random.randint(23) # it will generate number below 23
x6

5

In [33]:
x7 = np.random.randint(10,20)  # it will generate number between 10 to 20
x7

12

In [37]:
x8 = np.random.randint(10,20,4)  # it will generate '4' number between 10 to 20
x8

array([18, 12, 19, 11])

In [47]:
x9 = np.random.randint(5,50, size = (3,3))
x9

array([[47, 19, 22],
       [16, 12, 35],
       [30, 43, 16]])

In [58]:
x10 = np.random.randint(5,50,size = (4,3))
x10

array([[21, 10, 21],
       [22, 44, 16],
       [19, 43, 28],
       [47, 45, 16]])

### Choice

In [59]:
x11=np.random.choice([3,5,7,9])
x11

9

In [61]:
x12 = np.random.choice([3,5,7,9],size = (4,3))
x12

array([[7, 7, 9],
       [7, 3, 9],
       [3, 9, 7],
       [9, 5, 3]])