In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({ "col1" : [1,2,3,4,5],
               "col2" : [45,46,47,48,49],
               "col3" : "ineuron oneneuron great as well".split()
             })

# keys converted as column 

In [3]:
df

col1  col2       col3
0     1    45    ineuron
1     2    46  oneneuron
2     3    47      great
3     4    48         as
4     5    49       well

In [4]:
df['col4'] = df['col1']**2

In [5]:
df

col1  col2       col3  col4
0     1    45    ineuron     1
1     2    46  oneneuron     4
2     3    47      great     9
3     4    48         as    16
4     5    49       well    25

In [6]:
df['col5'] = df['col3'].str[0]

In [7]:
df

col1  col2       col3  col4 col5
0     1    45    ineuron     1    i
1     2    46  oneneuron     4    o
2     3    47      great     9    g
3     4    48         as    16    a
4     5    49       well    25    w

In [8]:
df['col5']

0    i
1    o
2    g
3    a
4    w
Name: col5, dtype: object

In [9]:
def test(a):
     return a**2
 

In [10]:
df['col4_4'] = df['col1'].apply(test)

In [11]:
df

col1  col2       col3  col4 col5  col4_4
0     1    45    ineuron     1    i       1
1     2    46  oneneuron     4    o       4
2     3    47      great     9    g       9
3     4    48         as    16    a      16
4     5    49       well    25    w      25

In [12]:
def test1(a):
    for i in a:
        if i != 'i':
            i = 'z'
        return i
             
        
          

In [13]:
df['col6'] = df['col5'].apply(test1)

In [14]:
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    45    ineuron     1    i       1    i
1     2    46  oneneuron     4    o       4    z
2     3    47      great     9    g       9    z
3     4    48         as    16    a      16    z
4     5    49       well    25    w      25    z

In [15]:
df['col6_6'] = df['col5'].apply(lambda a: 'z' if a !='i' else 'i')

In [16]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6
0     1    45    ineuron     1    i       1    i      i
1     2    46  oneneuron     4    o       4    z      z
2     3    47      great     9    g       9    z      z
3     4    48         as    16    a      16    z      z
4     5    49       well    25    w      25    z      z

In [17]:
df['col7'] = df['col3'].apply(len)

In [18]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45    ineuron     1    i       1    i      i     7
1     2    46  oneneuron     4    o       4    z      z     9
2     3    47      great     9    g       9    z      z     5
3     4    48         as    16    a      16    z      z     2
4     5    49       well    25    w      25    z      z     4

In [19]:
import math

In [20]:
df['col8'] = df['col2'].apply(math.log)

In [21]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45    ineuron     1    i       1    i      i     7  3.806662
1     2    46  oneneuron     4    o       4    z      z     9  3.828641
2     3    47      great     9    g       9    z      z     5  3.850148
3     4    48         as    16    a      16    z      z     2  3.871201
4     5    49       well    25    w      25    z      z     4  3.891820

In [2]:
import numpy as np

In [23]:
l = ["sudh", 1,2,3,4]

In [24]:
type(l)

list

In [25]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [26]:
type(np.array(l))
# n dimentional -nd

numpy.ndarray

In [27]:
a1 = np.array([3,4,5,6,3.0])

In [28]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [29]:
a = np.array([[1,2], [3,4]])

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
a[1,1]

4

In [32]:
a1

array([3., 4., 5., 6., 3.])

In [33]:
a1[1]

4.0

In [34]:
a2 = np.array([1,2,3,4], ndmin = 4)
#array inside array inside array

In [35]:
a2

array([[[[1, 2, 3, 4]]]])

In [36]:
a2[0][0][0][0]

1

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [40]:
np.mat([1,2,3,4,5])


matrix([[1, 2, 3, 4, 5]])

In [41]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [42]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [43]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [120]:
np.fromfunction(lambda i,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [49]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [3]:
np.fromfunction(lambda i, j, z: i*j*z, (3,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [4]:
np.fromfunction(lambda i, j, z: i*j*z, (4,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [4]:
a2 = np.fromfunction(lambda i, j, z: i*j*z, (4,3,2),dtype = int)

In [12]:
a2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [14]:
a2.ndim

3

In [16]:
a2.size
#Total element availablr

24

In [18]:
a2.shape

(4, 3, 2)

In [19]:
a2.dtype

dtype('int32')

In [21]:
a2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [23]:
a = a2 = np.fromfunction(lambda i, j: i*j, (4,3),dtype = int)

In [24]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [25]:
pd.DataFrame(a) 
# 2'd data can easily convert into dataframe

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [26]:
b = a = a2 = np.fromfunction(lambda i, j: i*j, (400,100),dtype = int)

In [27]:
pd.DataFrame(b)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [28]:
np.random.rand(100,4)

array([[0.12068161, 0.77418189, 0.08276044, 0.89877036],
       [0.79042496, 0.36905873, 0.95568863, 0.37533074],
       [0.98312296, 0.94037264, 0.09454904, 0.0731164 ],
       [0.05815419, 0.39827225, 0.04808842, 0.62650491],
       [0.66517057, 0.64593299, 0.52117122, 0.86861442],
       [0.93797084, 0.41168211, 0.41734887, 0.01543429],
       [0.44651563, 0.52726134, 0.70289022, 0.22842341],
       [0.8081881 , 0.71023238, 0.73169756, 0.56257525],
       [0.93980037, 0.34211328, 0.5634949 , 0.89810705],
       [0.157644  , 0.98445849, 0.99608847, 0.60480062],
       [0.37559891, 0.94940703, 0.9415793 , 0.83147809],
       [0.84785862, 0.576478  , 0.34888347, 0.11698014],
       [0.1496038 , 0.79270006, 0.24383588, 0.33029814],
       [0.51513034, 0.38827297, 0.18168005, 0.26559182],
       [0.62742367, 0.76248231, 0.34400554, 0.1428706 ],
       [0.41855995, 0.86474383, 0.1611251 , 0.71395895],
       [0.64315208, 0.92705017, 0.46026607, 0.80569847],
       [0.17893661, 0.54676693,

In [29]:
np.random.randint(4,50)

48

In [32]:
np.random.randn(4,5)

array([[ 1.29876978,  0.4240408 , -0.13242205, -1.22420721, -1.43716838],
       [ 0.34921514,  0.423655  ,  0.01956095, -0.14668832, -0.15928664],
       [-0.33091136, -1.1309795 , -0.45675587,  0.2269953 , -0.74552249],
       [-1.73462716, -0.32657115, -0.53831745, -2.04925729, -0.07458189]])

In [33]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.956955  1.319077 -0.917322  0.943111  0.159941
1  0.343113  0.249776 -0.035403  1.319065 -1.122647
2 -1.313805  0.818215 -1.186701  0.119807 -0.062002
3 -0.164282  0.286255 -1.110537 -1.085903 -1.250858

In [3]:
a

NameError: name 'a' is not defined

In [6]:
a2.ndim

3

In [7]:
a2.reshape(4,-124)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [8]:
a2.reshape(4,3,-1)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [10]:
list(range(4,10,2))

[4, 6, 8]

In [12]:
np.arange(4,10,.2)
#Here jump value taking .2 wherelse range fun cant take

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [14]:
np.arange(4,10.5,.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [15]:
a3 = np.arange(4,10.5,.2)

In [16]:
a3

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [17]:
a3[1:4]

array([4.2, 4.4, 4.6])

In [18]:
arr = np.random.rand(4,5)

In [19]:
arr

array([[0.8824079 , 0.03050714, 0.08532511, 0.40401549, 0.9023957 ],
       [0.93716342, 0.65778799, 0.09727412, 0.4492057 , 0.06711027],
       [0.986372  , 0.6279838 , 0.72295003, 0.69943734, 0.93075534],
       [0.28438829, 0.21011371, 0.96433448, 0.37946104, 0.17077547]])

In [20]:
arr > .5

array([[ True, False, False, False,  True],
       [ True,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False,  True, False, False]])

In [21]:
arr[arr > .5]

array([0.8824079 , 0.9023957 , 0.93716342, 0.65778799, 0.986372  ,
       0.6279838 , 0.72295003, 0.69943734, 0.93075534, 0.96433448])

In [22]:
arr

array([[0.8824079 , 0.03050714, 0.08532511, 0.40401549, 0.9023957 ],
       [0.93716342, 0.65778799, 0.09727412, 0.4492057 , 0.06711027],
       [0.986372  , 0.6279838 , 0.72295003, 0.69943734, 0.93075534],
       [0.28438829, 0.21011371, 0.96433448, 0.37946104, 0.17077547]])

In [24]:
arr[[1,2],[2]]

array([0.09727412, 0.72295003])

In [25]:
arr = np.random.rand(8,5)

In [26]:
arr

array([[0.09677077, 0.43999115, 0.09485175, 0.5102964 , 0.15031147],
       [0.60579969, 0.02252234, 0.13957005, 0.96772864, 0.18440568],
       [0.56743167, 0.40771285, 0.11720712, 0.00825791, 0.44912308],
       [0.90517626, 0.73070007, 0.63598701, 0.48940917, 0.23973414],
       [0.94152854, 0.20888568, 0.30160247, 0.31756262, 0.30796509],
       [0.06354644, 0.51346209, 0.96951072, 0.87343766, 0.17020202],
       [0.38909542, 0.50019024, 0.85095454, 0.80521476, 0.54355146],
       [0.15192026, 0.84167119, 0.79644073, 0.6487278 , 0.69776418]])

In [31]:
a2 = arr[1:8, [0,1,2]]

In [32]:
a2

array([[0.60579969, 0.02252234, 0.13957005],
       [0.56743167, 0.40771285, 0.11720712],
       [0.90517626, 0.73070007, 0.63598701],
       [0.94152854, 0.20888568, 0.30160247],
       [0.06354644, 0.51346209, 0.96951072],
       [0.38909542, 0.50019024, 0.85095454],
       [0.15192026, 0.84167119, 0.79644073]])

In [33]:
a2[0][0]

0.6057996947363885

In [34]:
a2[0][0] = 100

In [35]:
a2

array([[1.00000000e+02, 2.25223437e-02, 1.39570049e-01],
       [5.67431667e-01, 4.07712847e-01, 1.17207121e-01],
       [9.05176259e-01, 7.30700066e-01, 6.35987006e-01],
       [9.41528536e-01, 2.08885683e-01, 3.01602468e-01],
       [6.35464402e-02, 5.13462090e-01, 9.69510716e-01],
       [3.89095424e-01, 5.00190241e-01, 8.50954542e-01],
       [1.51920256e-01, 8.41671186e-01, 7.96440729e-01]])

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[2, 3],
       [4, 5]])

In [39]:
a*b
# this is element wise multiplication

array([[ 2,  6],
       [12, 20]])