In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(5)
# one dimentional array with all zeros by default

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [10]:
np.empty((4,5))

array([[6.23042070e-307, 7.56587584e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        1.60217812e-306, 1.37961370e-306],
       [1.42417629e-306, 1.37961913e-306, 1.42418172e-306,
        2.04712906e-306, 7.56589622e-307],
       [1.11258277e-307, 8.90111708e-307, 3.22643519e-307,
        9.79103798e-307, 2.46155235e-312]])

In [11]:
np.linspace(2,6,10)
# created some random value from startig value to end value and total 10 numbers

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [12]:
np.linspace(1,2,20).reshape(5,4)

array([[1.        , 1.05263158, 1.10526316, 1.15789474],
       [1.21052632, 1.26315789, 1.31578947, 1.36842105],
       [1.42105263, 1.47368421, 1.52631579, 1.57894737],
       [1.63157895, 1.68421053, 1.73684211, 1.78947368],
       [1.84210526, 1.89473684, 1.94736842, 2.        ]])

In [13]:
np.linspace(1,2,20,endpoint = False).reshape(5,4)
# here upper bounce will not be consider that is value"2 bcz of endpoint

array([[1.  , 1.05, 1.1 , 1.15],
       [1.2 , 1.25, 1.3 , 1.35],
       [1.4 , 1.45, 1.5 , 1.55],
       [1.6 , 1.65, 1.7 , 1.75],
       [1.8 , 1.85, 1.9 , 1.95]])

In [14]:
np.linspace(1,5,20,endpoint = False,retstep = True)
# step size is 0.2 here

(array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
        3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8]),
 0.2)

In [15]:
np.linspace(1,5,10,endpoint = False,retstep = True )

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)

In [16]:
np.logspace(2,4,10,base = 10)
# similar to linespace but here logarithmic value with log base

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [17]:
np.logspace(2,4,10,base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [18]:
a = np.arange(4,20).reshape(4,4)

In [19]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
a.max()

19

In [21]:
a = np.arange(4,40).reshape(6,6)

In [22]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [23]:
a.max()

39

In [24]:
a.max(axis = 0)

array([34, 35, 36, 37, 38, 39])

In [25]:
a.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [26]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [60]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [61]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [65]:
pow(a,2)
# similar to a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [66]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [67]:
 b = np.array([2,3,1,2,3,2])

In [68]:
b

array([2, 3, 1, 2, 3, 2])

In [75]:
b= b.reshape(1,-1)
b

array([[2, 3, 1, 2, 3, 2]])

In [69]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [77]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [76]:
b.T +a

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [78]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [79]:
np.sqrt(a)
# square root of every elements

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [80]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

### shallo copy and deep copy

In [99]:
x = np.array([1,2,3])

In [100]:
y = x
# shallo copy

In [101]:
y

array([1, 2, 3])

In [102]:
z = np.copy(x)
z
# here  z is not going to refer same location, it create new location
# this is deep copy

array([1, 2, 3])

In [103]:
x

array([1, 2, 3])

In [104]:
x[0] = 100

In [105]:
y

array([100,   2,   3])

In [97]:
z

array([1, 2, 3])

### Id function

In [108]:
id(x)

2807136905616

In [106]:
id(z)

2807127339824

In [107]:
id(y)

2807136905616

In [109]:
x = np.array([1,2,3])

In [112]:
y = x

In [113]:
id(x)

2807136905616

In [114]:
id(y)
# id of "x" and id of "y" is same here

2807136905616

In [115]:
id(x[0])

2807128840304

In [116]:
id(y[0])
# but element wise id is not same

2807128840368

In [118]:
id(x[0]) == id(y[0])
# but it is giving True

True

In [119]:
id(x[0]) == id(y[1])

True