## NumPy

In [197]:
! pip install numpy

In [198]:
import numpy as np

#### Version of NumPy 

In [199]:
print(np.__version__)

1.21.5


## Array

### Create Array by using array() Function

 -  - To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

#### Array by passing List

In [200]:
ar_list = np.array([1,2,3,4])


In [201]:
ar_list

array([1, 2, 3, 4])

In [202]:
type(ar_list)  # type of array is n dimentional array

numpy.ndarray

#### Array by passing Tuple

In [203]:
ar_tuple = np.array((5,6,7,8))

In [204]:
ar_tuple

array([5, 6, 7, 8])

#### Array by passing array

In [205]:
ar_array = np.array(ar_list)   # inside array function we have pass array

In [206]:
ar_array

array([1, 2, 3, 4])

## Dimensions in Array:-

#### 0- D Array

 - 0-D arrays are the elements in an array. Each value in an array is a 0-D array.

In [207]:
arr = np.array(84)

In [208]:
print(arr)

84


In [209]:
arr

array(84)

In [210]:
type(arr)

numpy.ndarray

In [211]:
arr.ndim 

0

### 1- D Array

 - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [212]:
arr1 = np.array([1,2,3,4])

In [213]:
print(arr1)

[1 2 3 4]


In [214]:
arr1.ndim

1

### 2-D Array

 - An array that has 1-D arrays as its elements is called a 2-D array.
 
 
  - 2-D array containing two arrays

#### Exmple_1

In [215]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [216]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [218]:
arr2.ndim

2

#### Exmple_2

In [219]:
arr2a = np.array(((1,2,3),(1,2,3)))

In [220]:
arr2a

array([[1, 2, 3],
       [1, 2, 3]])

In [221]:
print(arr2a)

[[1 2 3]
 [1 2 3]]


In [222]:
arr2a.ndim

2

### 3-D Array

 - An array that has 2-D arrays as its elements is called 3-D array.
    
    

##### Example_1

In [223]:
arr3 = np.array([[[1,2,3]],[[4,5,6]]])

In [224]:
arr3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [225]:
arr3.ndim

3

#### Example_2

In [226]:
arr3a = np.array(([[1,2],[3,4]],[[5,6],[7,8]]))

In [227]:
arr3a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [228]:
arr3a.ndim

3

In [229]:
a = np.array(42)
b = np.array([1, 2, 3])
c = np.array([[1, 2], [3,4]])
d = np.array([[[1, 2, 3], [4, 5, 6]]])

print(a,"dimension -",a.ndim,"\n")
print(b,"dimension -",b.ndim,"\n")
print(c,"dimension -",c.ndim,"\n")
print(d,"dimension -",d.ndim,"\n")

42 dimension - 0 

[1 2 3] dimension - 1 

[[1 2]
 [3 4]] dimension - 2 

[[[1 2 3]
  [4 5 6]]] dimension - 3 



#### Note : An array can have any number of dimensions.

### Create array with Dimension

In [230]:
arr_d = np.array([1,2,3,4],ndmin = 5)

In [231]:
arr_d

array([[[[[1, 2, 3, 4]]]]])

In [232]:
arr_d1 = np.array(([1,2,3],[4,5,6]),ndmin = 5)

In [233]:
arr_d1

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

### NumPy Array Indexing

 - Array indexing is the same as accessing an array element.
    
 - You can access an array element by referring to its index number.

 - The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1
    
    

In [234]:
arr_a = np.array([1,2,3,4])

In [235]:
arr_a

array([1, 2, 3, 4])

In [236]:
arr_a[0]

1

In [237]:
arr_a[2]

3

In [238]:
arr_a[1] +arr_a[2]

5

#### Access 2-D Arrays

In [239]:
arr_b = np.array([[1,2,3],[4,5,6]],ndmin = 2)

In [240]:
arr_b

array([[1, 2, 3],
       [4, 5, 6]])

In [241]:
arr_b[0,0]

1

In [242]:
arr_b[0,2]

3

In [243]:
arr_b[1,1]

5

In [244]:
arr_b[1,2]

6

### Access 3-D Arrays

In [245]:
arr_c = np.array([[1,2,3,4],[5,6,7,8]],ndmin=3)

In [246]:
print(arr_c)

[[[1 2 3 4]
  [5 6 7 8]]]


In [247]:
arr_c[0,0]

array([1, 2, 3, 4])

In [248]:
arr_c[0,0,1]

2

In [249]:
arr_c[0,1]

array([5, 6, 7, 8])

In [250]:
arr_c[0,1,2]

7

In [251]:
arr_d =np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [252]:
arr_d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [253]:
arr_d[1,0,1]

8

In [254]:
arr_d[0,1,2]

6

In [255]:
arr_d[1,1,1]

11

### NumPy Array Slicing

 
  - Slicing in python means taking elements from one given index to another given index.
    
    - [start:end:step]
    
 - If we don't pass start its considered 0



 - If we don't pass end its considered length of array in that dimension

    
 - If we don't pass step its considered 1

In [256]:
arr_s = np.array([1,2,3,4,5,6])

In [257]:
arr_s[1:5]

array([2, 3, 4, 5])

In [258]:
arr_s[4:]

array([5, 6])

In [259]:
arr_s[:4]

array([1, 2, 3, 4])

In [260]:
arr_s[-3:-1]

array([4, 5])

In [261]:
arr_s[3:-1]

array([4, 5])

In [262]:
arr_s[: : 2]

array([1, 3, 5])

### Slicing 2-D Arrays

In [263]:
arrs1 = np.array([[1,2,3,4],[5,6,7,8]])

In [264]:
arrs1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [265]:
arrs1[0,1:3]

array([2, 3])

In [266]:
arrs1[1,0:2]

array([5, 6])

In [267]:
arrs1[0:2,1]

array([2, 6])

In [268]:
arrs1[0:2,3]

array([4, 8])

In [269]:
arrs1[0:2,1:3]

array([[2, 3],
       [6, 7]])

### NumPy- Data Type

 - i - integer

 - b - boolean

 - u - unsigned integer

 - f - float

 - c - complex float

 - m - timedelta

 - M - datetime

 - O - object

 - S - string

 - U - unicode string

 - V - fixed chunk of memory for other type ( void )

#### dtype

In [270]:
arrt = np.array([1,2,3,4])

In [271]:
arrt.dtype

dtype('int32')

In [272]:
arrt1 = np.array(['apple','banana','cherry'])

In [273]:
arrt1.dtype

dtype('<U6')

#### Creating Arrays With a Defined Data Type

In [274]:
arrt2 = np.array([1,2,3,4],dtype = 'S')

In [275]:
arrt2

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [276]:
arrt2.dtype

dtype('S1')

In [277]:
arrt3 = np.array([1.2,2.2,4.1,3.2])

#### astype( ) - to change default data type into new data type

In [278]:
arrt3.astype('i')

array([1, 2, 4, 3], dtype=int32)

In [279]:
arrt4 =np.array([1,0,3,4])

In [280]:
arrt4.astype(bool)

array([ True, False,  True,  True])

### NumPy Array Copy V/S  View

####  1. Copy

In [281]:
arrc = np.array([1,2,3,4])

In [282]:
arrc

array([1, 2, 3, 4])

In [283]:
x= arrc.copy()

In [284]:
x

array([1, 2, 3, 4])

In [285]:
arrc[0]=43    # Assigning 42 value at 0th index in original array

In [286]:
arrc      # after assigning value

array([43,  2,  3,  4])

In [287]:
x           # copy of original array , which is not affected

array([1, 2, 3, 4])

#### 2. View

 - Which affect to original array

In [288]:
arrv = np.array([4,5,6,7])

In [289]:
x1 = arrv.view()  # creating view of array

In [290]:
x1      # view

array([4, 5, 6, 7])

In [291]:
x1[0] = 84   # assigning value to view 

In [292]:
arrv        # it has changed original array

array([84,  5,  6,  7])

In [293]:
x1

array([84,  5,  6,  7])

### Check if Array Owns its Data

 - Every NumPy array has the attribute base that returns None if the array owns the data.
    
    
 - Otherwise, the base  attribute refers to the original object.

In [294]:
arrcv = np.array([12,13,14,15])

In [295]:
x = arrcv.copy()   # copy own the data
y = arrcv.view()

In [296]:
print(x.base)
print(y.base)

None
[12 13 14 15]


### Shape

 - The shape of an array is the number of element in each dimension

In [297]:
arrs = np.array([[1,2,3,4],[5,6,7,8]])

In [298]:
arrs

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [299]:
arrs.shape

(2, 4)

In [300]:
arrs1 = np.array([1,2,3,4],ndmin =  5)

In [301]:
arrs1

array([[[[[1, 2, 3, 4]]]]])

In [302]:
arrs1.shape

(1, 1, 1, 1, 4)

### Reshape

In [303]:
arrr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [304]:
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [305]:
arrr.ndim

1

In [306]:
arrr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [307]:
arrr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [308]:
ar = np.array([1,2,3,4,5,6,7,8])

In [309]:
ar.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [310]:
ar.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [311]:
a = ar.reshape(2,2,-1)

In [312]:
a.ndim

3

### Flattening the arrays

 - Flattening array means converting a multidimensional array into a 1D array.

    
 - We can use reshape(-1) to do this.

In [313]:
arrs1

array([[[[[1, 2, 3, 4]]]]])

In [314]:
arrs1.reshape(-1)

array([1, 2, 3, 4])

### NumPy Array Iterating

In [315]:
arrn = np.array([1,2,3,4])
for i in arrn:
    print(i)

1
2
3
4


In [316]:
arrn1 = np.array([[1,2,3],[4,5,6]])

In [317]:
arrn1

array([[1, 2, 3],
       [4, 5, 6]])

In [318]:
for i in arrn1:
    print(i)

[1 2 3]
[4 5 6]


#### To iterate scalar element:

In [319]:
for i in arrn1:
    for j in i:
        print(j)

1
2
3
4
5
6


### nditer()

 - The function nditer() is a helping function that can be used from very basic to very advanced iterations.

 - It solves some basic issues which we face in iteration

 - In basic for loops, iterating through each scalar of an array we need to use n for loops
    
    which can be difficult to write for arrays with very high dimensionality.

In [320]:
for i in np.nditer(arrn1):
    print(i)

1
2
3
4
5
6


### NumPy Joining Array

 - Joining means putting contents of two or more arrays in a single array.
    
 - In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

## concatenate()

In [321]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
arr


array([1, 2, 3, 4, 5, 6])

### Concatenate 2'D array (axis=1):

In [322]:
arrj1 = np.array([[1,2,3],[4,5,6]])
arrj2 = np.array([[3,4,5],[7,8,9]])

arrj = np.concatenate((arrj1,arrj2),axis = 1)
arrj

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9]])

In [323]:
arrj1

array([[1, 2, 3],
       [4, 5, 6]])

### Concatenate 2'D array

In [324]:
arrj3 = np.array([[1,2,3],[4,5,6]])
arrj4 = np.array([[3,4,5],[7,8,9]])

arrj_1 = np.concatenate((arrj3,arrj4),axis = 0)
arrj_1

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [7, 8, 9]])

In [325]:
arrj_1.ndim

2

In [326]:
arrj3.ndim

2

In [327]:
stk = np.stack((arrj3,arrj4))
stk

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [7, 8, 9]]])

### Concatenate 3'D array

In [328]:
arv = np.arange(1,7).reshape(1,2,3)
arv

array([[[1, 2, 3],
        [4, 5, 6]]])

In [329]:
arv2 = np.arange(7,13).reshape(1,2,3)
arv2

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [330]:
arvv = np.concatenate((arv,arv2))
arvv

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Stack( )

 - Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
 
    
 - We pass a sequence of arrays that we want to join to the stack() method along with the axis.

 If axis is not explicitly passed it is taken as 0.

In [396]:
arrs1 = np.array([1,2,3])
arrs2 = np.array([4,5,6])
arrs = np.stack((arrs1,arrs2),axis = 0)
arrs

array([[1, 2, 3],
       [4, 5, 6]])

In [395]:
np.concatenate((arrs1,arrs2))

array([1, 2, 3, 4, 5, 6])

### H-stack

In [332]:
arrhs = np.hstack((arrs1,arrs2))
arrhs

array([1, 2, 3, 4, 5, 6])

### V-stack

In [333]:
arrvs = np.vstack((arrs1,arrs2))
arrvs

array([[1, 2, 3],
       [4, 5, 6]])

### Splitting NumPy Arrays

 - Splitting is reverse operation of Joining.
 
 
 - Joining merges multiple arrays into one and Splitting breaks one array into multiple.
 
 
 - We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

#### array_split()

Syntax:
    
    array_split(array_name,spliting number)

In [334]:
sarr = np.arange(1,7)

In [335]:
sarr

array([1, 2, 3, 4, 5, 6])

In [336]:
np.array_split(sarr,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [337]:
sarr2 = np.arange(2,20,2)

In [338]:
sarr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [339]:
np.array_split(sarr2,3)

[array([2, 4, 6]), array([ 8, 10, 12]), array([14, 16, 18])]

#### Split with 2'D

In [340]:
arr_s = np.array([[ 1,  2,  3],  [4,  5,  6] ,[ 7,  8,  9], [10, 11, 12], [13, 14, 15], [16, 17,18]])

In [341]:
arr_s

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [342]:
np.array_split(arr_s,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [343]:
np.array_split(arr_s,2,axis = 1)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

### dstack()

In [344]:
a = np.array([1, 2])
b = np.array([4, 5])
c = np.dstack((a,b))
c

array([[[1, 4],
        [2, 5]]])

### Numpy Splitting Array

In [345]:
arr = np.array([1,2,3,4,5,6])
np.array_split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

#### Splitting 2-D Arrays

In [346]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arr, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

#### Split the 2-D array into three 2-D arrays.

In [347]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

np.array_split(arr, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

#### Split the 2-D array into three 2-D arrays along rows

In [348]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.array_split(arr,3,axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

#### hsplit ( ) - 

In [349]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

np.hsplit(arr, 3)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

### NumPy Searching Arrays

#### Find the indexes where the value is 4:

In [350]:
arr_srch = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr_srch == 4)


(array([3, 5, 6], dtype=int64),)

#### Find the indexes where the values are even:

In [351]:

arr_evn = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.where(arr_evn %2 == 0)

(array([1, 3, 5, 7], dtype=int64),)

#### Find the indexes where the values are odd:

In [352]:
arr_evn = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.where(arr_evn %2 != 0)

(array([0, 2, 4, 6], dtype=int64),)

______________________________________________________________

### searchsorted()

#### Find the indexes where the value 7 

In [353]:
arr_ = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.searchsorted(arr_,7)

6

In [354]:
arr_ = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.searchsorted(arr_,[3,4,7])

array([2, 3, 6], dtype=int64)

____________________________________________________________________________________

### Sorting Array

 - Sorting means putting elements in an ordered sequence.

    
 - Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

### Sort()

In [355]:
arr_srt = np.array([1,3,5,3,35,5])
np.sort(arr_srt)

array([ 1,  3,  3,  5,  5, 35])

In [356]:
arr_srt1 = np.array([[2,5,3],[9,6,8]])
np.sort(arr_srt1)

array([[2, 3, 5],
       [6, 8, 9]])

In [357]:
arr_srt2 = np.array([True,False,True])
np.sort(arr_srt2)

array([False,  True,  True])

### Filtering Arrays

In [358]:
arrF = np.array([41, 42, 43, 44])

x = [True, False, True, False]

x1= arrF[x]
x1


array([41, 43])

______________________________________________________________________________________________________________

## Random

 - Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

NumPy offers the **random** module to work with random numbers.

In [359]:
from numpy import random
x = random.random(5)
x

array([0.3164379 , 0.13598275, 0.92606873, 0.97044127, 0.83459248])

In [360]:
x1 = random.randint(80,90)
x1

81

In [361]:
x2 = random.randint(80,90,size = 4)
x2

array([81, 81, 87, 87])

In [362]:
x3 = random.randint(1,30,size = (3,4))
x3

array([[ 3,  1, 12,  5],
       [ 5,  7,  7,  1],
       [ 1,  5, 18, 19]])

In [363]:
x3 = random.rand(4,3)
x3

array([[0.78718614, 0.68403358, 0.32990997],
       [0.65678979, 0.15974103, 0.78167609],
       [0.44160507, 0.87738038, 0.80434342],
       [0.35439159, 0.14887637, 0.43839989]])

### Arange( )

 - np.arange() can also be used to create a numpy array

 - the numbers generated have same difference 

 - the function generates as many possible numbers in the given range

 - arange(stop): Values are generated within the half-open interval [0, stop) (in other words, the interval including start but excluding stop).
 

 - arange(start, stop): Values are generated within the half-open interval [start, stop).


 - arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step.

![](arange.png)

In [364]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [365]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [366]:
np.arange(10,20) # step is not given, it takes by default 1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [367]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [368]:
np.arange(10,20,1.3)

array([10. , 11.3, 12.6, 13.9, 15.2, 16.5, 17.8, 19.1])

In [369]:
np.arange(10,20,1,dtype = 'f')

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [370]:
np.arange(-3,3,1,dtype = int)

array([-3, -2, -1,  0,  1,  2])

In [371]:
np.arange(-3,3,0.5,dtype = int)  #Precision loss can occur here, due to casting or due to using floating points when start is much larger than step. This can lead to unexpected behaviour. For example:

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

__________________________________________________________________________________________________________________

### Linespace( )

 - linspace() generates a specified number of values in a specified range

#### Syntax

 - numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

**start**

The starting value of the sequence.

**stop**

The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.


**num = ** int, optional

Number of samples to generate. Default is 50. Must be non-negative.


**endpoint** bool, optional
If True, stop is the last sample. Otherwise, it is not included. Default is True.


**retstep** bool, optional

If True, return (samples, step), where step is the spacing between samples.


**dtype**, optional

The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.


**axis**  int, optional

The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.

In [372]:
np.linspace(5,50,4)

array([ 5., 20., 35., 50.])

In [373]:
np.linspace(5,50,4,dtype = int)

array([ 5, 20, 35, 50])

In [374]:
np.linspace(5,50,4,retstep = True)   # it return (sample,step)

(array([ 5., 20., 35., 50.]), 15.0)

In [375]:
np.linspace(1,100,4, endpoint=True)

array([  1.,  34.,  67., 100.])

In [376]:
np.linspace(1,100,4,endpoint=False) # endpoint false, it will not taking end value

array([ 1.  , 25.75, 50.5 , 75.25])

In [377]:
np.linspace(1,100,4,endpoint=False).astype('i')

array([ 1, 25, 50, 75], dtype=int32)

In [378]:
np.linspace(10,50,5,endpoint = False,retstep = True,dtype = str)

(array(['10.0', '18.0', '26.0', '34.0', '42.0'], dtype='<U32'), 8.0)

### Zeros( ) 

#### Syntax : 

**np.zeros**( shape, dtype = **float** , order = 'C', *, like = None )

In [379]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [380]:
np.zeros(4,str)

array(['', '', '', ''], dtype='<U1')

In [381]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [382]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Empty()

In [383]:
np.empty(2)

array([1.35465896e-311, 0.00000000e+000])

In [384]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [385]:
np.empty([2,3],dtype = int)

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

### Full

In [386]:
np.full((3,2),fill_value='vijay')

array([['vijay', 'vijay'],
       ['vijay', 'vijay'],
       ['vijay', 'vijay']], dtype='<U5')

In [387]:
np.full((3,2),fill_value=84)

array([[84, 84],
       [84, 84],
       [84, 84]])

### Identity()

In [388]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [389]:
np.identity(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Eye()

#### Syntax

numpy.eye( N, M = None, k = 0, dtype = <class 'float'>, order = 'C', *, like = None)


In [390]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [391]:
np.eye(3,3,1,dtype = int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [392]:
np.eye(3,3,-1,dtype = int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])